<a href="https://colab.research.google.com/github/Nitinprasadsingh/Synapse/blob/main/nsrdb_data_prepfirst2years(final).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/NSRDB_cleaned_data.csv")

In [ ]:
df.describe()

,Year,Month,Day,Hour,Minute,Temperature,Wind Speed,Wind Direction,Pressure,Solar Zenith Angle,DNI,GHI,DHI,Relative Humidity,Dew Point,Hour_sin,Hour_cos,DayOfYear,Target_GHI
count,105104.000000,105104.000000,105104.000000,105104.000000,105104.00000,105104.000000,105104.000000,105104.000000,105104.000000,105104.000000,105104.000000,105104.000000,105104.000000,105104.000000,105104.000000,1.051040e+05,1.051040e+05,105104.000000,105104.000000
mean,2017.999848,6.525194,15.718222,11.498478,22.50000,25.925544,2.194551,219.839816,1007.314546,89.749682,139.205787,196.293119,102.842956,76.595617,20.696438,8.874833e-05,-1.156591e-04,182.972294,196.293119
std,0.816469,3.447469,8.794938,6.921633,16.77059,6.112343,1.215967,84.807749,6.333118,43.981186,220.964791,279.505233,139.968609,21.154516,6.657926,7.071218e-01,7.070985e-01,105.350617,279.505233
min,2017.000000,1.000000,1.000000,0.000000,0.00000,5.400000,0.100000,0.000000,989.000000,0.690000,0.000000,0.000000,0.000000,9.310000,-2.700000,-1.000000e+00,-1.000000e+00,1.000000,0.000000
25%,2017.000000,4.000000,8.000000,5.000000,11.25000,22.600000,1.300000,178.000000,1002.000000,51.900000,0.000000,0.000000,0.000000,63.450000,15.700000,-7.071068e-01,-7.071068e-01,92.000000,0.000000
50%,2018.000000,7.000000,16.000000,11.000000,22.50000,27.000000,1.900000,209.000000,1008.000000,89.310000,0.000000,0.000000,0.000000,81.780000,23.100000,1.224647e-16,-1.836970e-16,183.000000,0.000000
75%,2019.000000,10.000000,23.000000,17.000000,33.75000,29.600000,2.900000,297.000000,1013.000000,127.790000,240.000000,388.000000,204.000000,95.120000,26.500000,7.071068e-01,7.071068e-01,274.000000,388.000000
max,2019.000000,12.000000,31.000000,23.000000,45.00000,42.300000,9.700000,360.000000,1022.000000,179.580000,931.000000,1028.000000,516.000000,100.000000,29.200000,1.000000e+00,1.000000e+00,365.000000,1028.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105104 entries, 0 to 105103
Data columns (total 20 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   datetime            105104 non-null  object
 1   Year                105104 non-null  int64
 2   Month               105104 non-null  int64
 3   Day                 105104 non-null  int64
 4   Hour                105104 non-null  int64
 5   Minute              105104 non-null  int64
 6   Temperature         105104 non-null  float64
 7   Wind Speed          105104 non-null  float64
 8   Wind Direction      105104 non-null  int64
 9   Pressure            105104 non-null  int64
 10  Solar Zenith Angle  105104 non-null  float64
 11  DNI                 105104 non-null  int64
 12  GHI                 105104 non-null  int64
 13  DHI                 105104 non-null  int64
 14  Relative Humidity   105104 non-null  float64
 15  Dew Point           105104 non-null  float64
 16  Hour_sin            105104 non-null  float64
 17  Hour_cos            105104 non-null  float64
 18  DayOfYear           105104 non-null  int64
 19  Target_GHI          105104 non-null  float64
dtypes: float64(8), int64(11), object(1)
memory usage: 16.0+ MB

In [ ]:
# Ensure datetime is a Datetime object and set it as the index for resampling
df['datetime'] = pd.to_datetime(df['datetime'])
df_indexed = df.set_index('datetime')

# Resample using 'h' (lowercase) to avoid the future warning
df_hourly = df_indexed.resample('h').mean()
print(df_hourly.head())

                       Year  Month  Day  Hour  Minute  Temperature  \
datetime
2017-01-01 00:00:00  2017.0    1.0  1.0   0.0    22.5       14.850
2017-01-01 01:00:00  2017.0    1.0  1.0   1.0    22.5       13.825
2017-01-01 02:00:00  2017.0    1.0  1.0   2.0    22.5       13.050
2017-01-01 03:00:00  2017.0    1.0  1.0   3.0    22.5       12.400
2017-01-01 04:00:00  2017.0    1.0  1.0   4.0    22.5       12.000

                     Wind Speed  Wind Direction  Pressure  Solar Zenith Angle  \
datetime
2017-01-01 00:00:00       1.225          324.50   1012.00            163.2950
2017-01-01 01:00:00       1.300          327.25   1011.75            149.5275
2017-01-01 02:00:00       1.300          330.50   1011.00            135.8450
2017-01-01 03:00:00       1.350          334.50   1011.50            122.2975
2017-01-01 04:00:00       1.400          337.00   1012.00            108.9700

                     DNI  GHI  DHI  Relative Humidity  Dew Point  Hour_sin  \
datetime
2017-01-01 00:00:00  0.0  0.0  0.0            91.6550     13.475  0.000000
2017-01-01 01:00:00  0.0  0.0  0.0            94.8025     12.975  0.258819
2017-01-01 02:00:00  0.0  0.0  0.0            96.3875     12.475  0.500000
2017-01-01 03:00:00  0.0  0.0  0.0            97.4175     12.000  0.707107
2017-01-01 04:00:00  0.0  0.0  0.0            97.8300     11.700  0.866025

                     Hour_cos  DayOfYear  Target_GHI
datetime
2017-01-01 00:00:00  1.000000        1.0        0.00
2017-01-01 01:00:00  0.965926        1.0        0.00
2017-01-01 02:00:00  0.866025        1.0       49.00
2017-01-01 03:00:00  0.707107        1.0      218.00
2017-01-01 04:00:00  0.500000        1.0      396.25

In [ ]:
df_hourly

,Year,Month,Day,Hour,Minute,Temperature,Wind Speed,Wind Direction,Pressure,Solar Zenith Angle,DNI,GHI,DHI,Relative Humidity,Dew Point,Hour_sin,Hour_cos,DayOfYear,Target_GHI
datetime,,,,,,,,,,,,,,,,,,,
2017-01-01 00:00:00,2017.0,1.0,1.0,0.0,22.5,14.850,1.225,324.50,1012.00,163.2950,0.0,0.00,0.00,91.6550,13.475,0.000000,1.000000e+00,1.0,0.00
2017-01-01 01:00:00,2017.0,1.0,1.0,1.0,22.5,13.825,1.300,327.25,1011.75,149.5275,0.0,0.00,0.00,94.8025,12.975,0.258819,9.659258e-01,1.0,0.00
2017-01-01 02:00:00,2017.0,1.0,1.0,2.0,22.5,13.050,1.300,330.50,1011.00,135.8450,0.0,0.00,0.00,96.3875,12.475,0.500000,8.660254e-01,1.0,49.00
2017-01-01 03:00:00,2017.0,1.0,1.0,3.0,22.5,12.400,1.350,334.50,1011.50,122.2975,0.0,0.00,0.00,97.4175,12.000,0.707107,7.071068e-01,1.0,218.00
2017-01-01 04:00:00,2017.0,1.0,1.0,4.0,22.5,12.000,1.400,337.00,1012.00,108.9700,0.0,0.00,0.00,97.8300,11.700,0.866025,5.000000e-01,1.0,396.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-12-31 15:00:00,2019.0,12.0,31.0,15.0,22.5,18.950,1.025,311.50,1016.00,76.4825,249.0,164.50,103.25,74.0125,14.200,-0.707107,-7.071068e-01,365.0,0.00
2019-12-31 16:00:00,2019.0,12.0,31.0,16.0,22.5,16.925,1.150,307.00,1016.75,88.4475,38.0,17.25,14.00,73.7725,12.225,-0.866025,-5.000000e-01,365.0,0.00
2019-12-31 17:00:00,2019.0,12.0,31.0,17.0,22.5,16.025,1.200,306.00,1017.50,101.4025,0.0,0.00,0.00,74.0425,11.400,-0.965926,-2.588190e-01,365.0,0.00
2019-12-31 18:00:00,2019.0,12.0,31.0,18.0,22.5,15.350,1.225,305.00,1018.00,114.5575,0.0,0.00,0.00,75.0775,10.975,-1.000000,-1.836970e-16,365.0,0.00
2019-12-31 19:00:00,2019.0,12.0,31.0,19.0,22.5,14.750,1.300,305.50,1019.00,127.9825,0.0,0.00,0.00,75.9675,10.525,-0.965926,2.588190e-01,365.0,0.00

In [ ]:
df_2018 = df_hourly.loc['2018-01-01':'2018-12-31']
print(df_2018.head())
print(df_2018.tail())

                       Year  Month  Day  Hour  Minute  Temperature  \
datetime
2018-01-01 00:00:00  2018.0    1.0  1.0   0.0    22.5       10.600
2018-01-01 01:00:00  2018.0    1.0  1.0   1.0    22.5       10.000
2018-01-01 02:00:00  2018.0    1.0  1.0   2.0    22.5        9.475
2018-01-01 03:00:00  2018.0    1.0  1.0   3.0    22.5        8.975
2018-01-01 04:00:00  2018.0    1.0  1.0   4.0    22.5        8.600

                     Wind Speed  Wind Direction  Pressure  Solar Zenith Angle  \
datetime
2018-01-01 00:00:00       1.675          328.75    1018.0            163.2675
2018-01-01 01:00:00       1.725          334.00    1018.0            149.4975
2018-01-01 02:00:00       1.800          340.25    1018.0            135.8175
2018-01-01 03:00:00       1.900          346.25    1018.0            122.2775
2018-01-01 04:00:00       1.900          350.00    1018.0            108.9450

                     DNI  GHI  DHI  Relative Humidity  Dew Point  Hour_sin  \
datetime
2018-01-01 00:00:00  0.0  0.0  0.0            81.2675      7.525  0.000000
2018-01-01 01:00:00  0.0  0.0  0.0            82.5175      7.200  0.258819
2018-01-01 02:00:00  0.0  0.0  0.0            83.2425      6.800  0.500000
2018-01-01 03:00:00  0.0  0.0  0.0            83.7800      6.400  0.707107
2018-01-01 04:00:00  0.0  0.0  0.0            84.2300      6.100  0.866025

                     Hour_cos  DayOfYear  Target_GHI
datetime
2018-01-01 00:00:00  1.000000        1.0        0.00
2018-01-01 01:00:00  0.965926        1.0        0.00
2018-01-01 02:00:00  0.866025        1.0       62.25
2018-01-01 03:00:00  0.707107        1.0      249.00
2018-01-01 04:00:00  0.500000        1.0      431.25
                       Year  Month   Day  Hour  Minute  Temperature  \
datetime
2018-12-31 19:00:00  2018.0   12.0  31.0  19.0    22.5       13.800
2018-12-31 20:00:00  2018.0   12.0  31.0  20.0    22.5       13.125
2018-12-31 21:00:00  2018.0   12.0  31.0  21.0    22.5       12.450
2018-12-31 22:00:00  2018.0   12.0  31.0  22.0    22.5       11.850
2018-12-31 23:00:00  2018.0   12.0  31.0  23.0    22.5       11.200

                     Wind Speed  Wind Direction  Pressure  Solar Zenith Angle  \
datetime
2018-12-31 19:00:00         1.5          309.75    1018.0            127.9550
2018-12-31 20:00:00         1.5          310.75    1018.0            141.5625
2018-12-31 21:00:00         1.6          313.75    1018.0            155.2825
2018-12-31 22:00:00         1.6          318.75    1018.0            169.0625
2018-12-31 23:00:00         1.6          324.00    1018.0            175.8800

                     DNI  GHI  DHI  Relative Humidity  Dew Point  Hour_sin  \
datetime
2018-12-31 19:00:00  0.0  0.0  0.0            73.5000      9.125 -0.965926
2018-12-31 20:00:00  0.0  0.0  0.0            74.9100      8.800 -0.866025
2018-12-31 21:00:00  0.0  0.0  0.0            76.6025      8.425 -0.707107
2018-12-31 22:00:00  0.0  0.0  0.0            78.1100      8.125 -0.500000
2018-12-31 23:00:00  0.0  0.0  0.0            79.8775      7.825 -0.258819

                     Hour_cos  DayOfYear  Target_GHI
datetime
2018-12-31 19:00:00  0.258819      365.0         0.0
2018-12-31 20:00:00  0.500000      365.0         0.0
2018-12-31 21:00:00  0.707107      365.0         0.0
2018-12-31 22:00:00  0.866025      365.0         0.0
2018-12-31 23:00:00  0.965926      365.0         0.0

In [ ]:
df_2018.describe()

,Year,Month,Day,Hour,Minute,Temperature,Wind Speed,Wind Direction,Pressure,Solar Zenith Angle,DNI,GHI,DHI,Relative Humidity,Dew Point,Hour_sin,Hour_cos,DayOfYear,Target_GHI
count,8760.0,8760.000000,8760.000000,8760.000000,8760.0,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.00000,8.760000e+03,8.760000e+03,8760.000000,8760.000000
mean,2018.0,6.526027,15.720548,11.500000,22.5,25.582751,2.083202,225.150571,1007.084618,89.760499,139.579252,197.201598,103.620491,75.751439,20.23389,-1.845302e-17,-5.546046e-17,183.000000,197.201598
std,0.0,3.448048,8.796749,6.922582,0.0,6.172718,1.090796,81.082179,6.454886,43.866844,213.661742,275.942181,138.402535,20.604859,6.79628,7.071471e-01,7.071471e-01,105.372043,275.942181
min,2018.0,1.000000,1.000000,0.000000,22.5,6.300000,0.100000,1.250000,991.000000,3.810000,0.000000,0.000000,0.000000,14.832500,2.35000,-1.000000e+00,-1.000000e+00,1.000000,0.000000
25%,2018.0,4.000000,8.000000,5.750000,22.5,22.150000,1.225000,179.500000,1002.000000,51.940000,0.000000,0.000000,0.000000,62.363750,14.67500,-7.071068e-01,-7.071068e-01,92.000000,0.000000
50%,2018.0,7.000000,16.000000,11.500000,22.5,26.875000,1.850000,220.000000,1008.000000,90.270000,0.000000,5.000000,4.750000,79.832500,22.55000,6.123234e-17,-6.123234e-17,183.000000,5.000000
75%,2018.0,10.000000,23.000000,17.250000,22.5,29.525000,2.775000,298.812500,1012.000000,127.789375,247.812500,391.187500,206.312500,94.192500,26.37500,7.071068e-01,7.071068e-01,274.000000,391.187500
max,2018.0,12.000000,31.000000,23.000000,22.5,40.325000,7.275000,359.000000,1021.000000,176.337500,912.500000,964.000000,505.500000,100.000000,28.65000,1.000000e+00,1.000000e+00,365.000000,964.000000

### Data Quality Checks for `df_2018`
We will evaluate the dataset for missing values, duplicates, and logical inconsistencies (like non-zero solar radiation at night).

In [ ]:
import pandas as pd
import numpy as np

# Re-loading data since kernel state was lost
try:
    # Attempt to load the original dataset
    # Note: If the file is not in /content/, please ensure it is uploaded.
    df = pd.read_csv('/content/NSRDB_cleaned_data.csv')
    df['datetime'] = pd.to_datetime(df['datetime'])
    df.set_index('datetime', inplace=True)

    # Re-creating the hourly 2018 slice
    df_hourly = df.resample('h').mean()
    df_2018 = df_hourly.loc['2018-01-01':'2018-12-31']

    print("--- Data Quality Checks for df_2018 ---")

    # 1. Check for missing values
    print("\n1. Missing Values:")
    print(df_2018.isnull().sum())

    # 2. Check for duplicate timestamps
    print("\n2. Duplicate Timestamps:")
    print(f"Number of duplicates in index: {df_2018.index.duplicated().sum()}")

    # 3. Check for night-time values (Solar Zenith Angle > 90 should have 0 GHI/DNI)
    night_data = df_2018[df_2018['Solar Zenith Angle'] > 95]
    non_zero_night = night_data[(night_data['GHI'] > 0) | (night_data['DNI'] > 0)]

    print("\n3. Logical Consistency (Night-time Solar):")
    print(f"Number of night-time records with non-zero solar values: {len(non_zero_night)}")

    # 4. Check for Value Ranges
    print("\n4. Value Ranges (Outlier Check):")
    display(df_2018[['Temperature', 'Pressure', 'Relative Humidity', 'GHI']].agg(['min', 'max']))

except FileNotFoundError:
    print("Error: 'NSRDB_cleaned_data.csv' not found in /content/. Please upload the file or adjust the path.")
except Exception as e:
    print(f"An error occurred: {e}")

--- Data Quality Checks for df_2018 ---

1. Missing Values:
Year                  0
Month                 0
Day                   0
Hour                  0
Minute                0
Temperature           0
Wind Speed            0
Wind Direction        0
Pressure              0
Solar Zenith Angle    0
DNI                   0
GHI                   0
DHI                   0
Relative Humidity     0
Dew Point             0
Hour_sin              0
Hour_cos              0
DayOfYear             0
Target_GHI            0
dtype: int64

2. Duplicate Timestamps:
Number of duplicates in index: 0

3. Logical Consistency (Night-time Solar):
Number of night-time records with non-zero solar values: 0

4. Value Ranges (Outlier Check):

     Temperature  Pressure  Relative Humidity    GHI
min        6.300     991.0            14.8325    0.0
max       40.325    1021.0           100.0000  964.0

In [ ]:
df_2018.columns

Index(['Year', 'Month', 'Day', 'Hour', 'Minute', 'Temperature', 'Wind Speed',
       'Wind Direction', 'Pressure', 'Solar Zenith Angle', 'DNI', 'GHI', 'DHI',
       'Relative Humidity', 'Dew Point', 'Hour_sin', 'Hour_cos', 'DayOfYear',
       'Target_GHI'],
      dtype='object')

In [ ]:


# --------------------------------------------------
# Load dataset
# --------------------------------------------------
df = df_2018.copy()

# --------------------------------------------------
# PV system assumptions
# --------------------------------------------------
PV_CAPACITY_KW = 100       # Installed PV capacity
SYSTEM_EFFICIENCY = 0.80   # 80% overall efficiency/derating
PANEL_TILT_DEG = 33        # Assumed fixed panel tilt

# --------------------------------------------------
# Convert angles from degrees to radians
# --------------------------------------------------
solar_zenith_rad = np.radians(df["Solar Zenith Angle"])
panel_tilt_rad = np.radians(PANEL_TILT_DEG)

# --------------------------------------------------
# Calculate beam/direct irradiance on panel
#
# Simplified assumption:
# Angle of incidence ≈ Solar Zenith Angle - Panel Tilt
# --------------------------------------------------
angle_of_incidence = solar_zenith_rad - panel_tilt_rad

beam_poa = (
    df["DNI"] * np.cos(angle_of_incidence)
)

# --------------------------------------------------
# Calculate diffuse irradiance on tilted panel
# Isotropic sky model
# --------------------------------------------------
diffuse_poa = (
    df["DHI"] * (1 + np.cos(panel_tilt_rad)) / 2
)

# --------------------------------------------------
# Total Plane-of-Array irradiance
# --------------------------------------------------
df["POA_Irradiance"] = beam_poa + diffuse_poa

# Remove physically impossible negative irradiance
df["POA_Irradiance"] = df["POA_Irradiance"].clip(lower=0)

# --------------------------------------------------
# Calculate PV output
# --------------------------------------------------
df["PV_Output_kW"] = (
    PV_CAPACITY_KW
    * (df["POA_Irradiance"] / 1000)
    * SYSTEM_EFFICIENCY
)

# Make sure output cannot exceed installed capacity
df["PV_Output_kW"] = df["PV_Output_kW"].clip(
    lower=0,
    upper=PV_CAPACITY_KW
)

# --------------------------------------------------
# Save updated dataset
# --------------------------------------------------
df.to_csv("dataset_with_pv.csv", index=False)

# --------------------------------------------------
# Check results
# --------------------------------------------------
print(
    df[
        [
            "Year",
            "Month",
            "Day",
            "Hour",
            "DNI",
            "DHI",
            "Solar Zenith Angle",
            "POA_Irradiance",
            "PV_Output_kW"
        ]
    ].head(20)
)

                       Year  Month  Day  Hour     DNI     DHI  \
datetime
2018-01-01 00:00:00  2018.0    1.0  1.0   0.0    0.00    0.00
2018-01-01 01:00:00  2018.0    1.0  1.0   1.0    0.00    0.00
2018-01-01 02:00:00  2018.0    1.0  1.0   2.0    0.00    0.00
2018-01-01 03:00:00  2018.0    1.0  1.0   3.0    0.00    0.00
2018-01-01 04:00:00  2018.0    1.0  1.0   4.0    0.00    0.00
2018-01-01 05:00:00  2018.0    1.0  1.0   5.0    0.00    0.00
2018-01-01 06:00:00  2018.0    1.0  1.0   6.0  139.50   41.50
2018-01-01 07:00:00  2018.0    1.0  1.0   7.0  431.75  110.50
2018-01-01 08:00:00  2018.0    1.0  1.0   8.0  579.25  150.50
2018-01-01 09:00:00  2018.0    1.0  1.0   9.0  656.50  174.25
2018-01-01 10:00:00  2018.0    1.0  1.0  10.0  409.50  281.75
2018-01-01 11:00:00  2018.0    1.0  1.0  11.0  150.75  299.25
2018-01-01 12:00:00  2018.0    1.0  1.0  12.0  111.75  310.00
2018-01-01 13:00:00  2018.0    1.0  1.0  13.0   42.50  193.75
2018-01-01 14:00:00  2018.0    1.0  1.0  14.0    0.00   35.25
2018-01-01 15:00:00  2018.0    1.0  1.0  15.0    6.50   46.75
2018-01-01 16:00:00  2018.0    1.0  1.0  16.0    0.00    8.00
2018-01-01 17:00:00  2018.0    1.0  1.0  17.0    0.00    0.00
2018-01-01 18:00:00  2018.0    1.0  1.0  18.0    0.00    0.00
2018-01-01 19:00:00  2018.0    1.0  1.0  19.0    0.00    0.00

                     Solar Zenith Angle  POA_Irradiance  PV_Output_kW
datetime
2018-01-01 00:00:00            163.2675        0.000000      0.000000
2018-01-01 01:00:00            149.4975        0.000000      0.000000
2018-01-01 02:00:00            135.8175        0.000000      0.000000
2018-01-01 03:00:00            122.2775        0.000000      0.000000
2018-01-01 04:00:00            108.9450        0.000000      0.000000
2018-01-01 05:00:00             95.9600        0.000000      0.000000
2018-01-01 06:00:00             83.2825      127.293303     10.183464
2018-01-01 07:00:00             71.6350      438.843407     35.107473
2018-01-01 08:00:00             61.1225      649.224766     51.937981
2018-01-01 09:00:00             52.5650      778.789303     62.303144
2018-01-01 10:00:00             47.0625      656.250514     52.500041
2018-01-01 11:00:00             45.7125      422.165682     33.773255
2018-01-01 12:00:00             48.8525      392.493873     31.399510
2018-01-01 13:00:00             55.7475      217.315470     17.385238
2018-01-01 14:00:00             65.2150       32.406569      2.592526
2018-01-01 15:00:00             76.2825       47.710809      3.816865
2018-01-01 16:00:00             88.2575        7.354682      0.588375
2018-01-01 17:00:00            101.2075        0.000000      0.000000
2018-01-01 18:00:00            114.3650        0.000000      0.000000
2018-01-01 19:00:00            127.7975        0.000000      0.000000

In [ ]:
df.columns

Index(['Year', 'Month', 'Day', 'Hour', 'Minute', 'Temperature', 'Wind Speed',
       'Wind Direction', 'Pressure', 'Solar Zenith Angle', 'DNI', 'GHI', 'DHI',
       'Relative Humidity', 'Dew Point', 'Hour_sin', 'Hour_cos', 'DayOfYear',
       'Target_GHI', 'POA_Irradiance', 'PV_Output_kW'],
      dtype='object')

In [ ]:
df["PV_target"] = df["PV_Output_kW"].shift(-1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 8760 entries, 2018-01-01 00:00:00 to 2018-12-31 23:00:00
Freq: h
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Year                8760 non-null   float64
 1   Month               8760 non-null   float64
 2   Day                 8760 non-null   float64
 3   Hour                8760 non-null   float64
 4   Minute              8760 non-null   float64
 5   Temperature         8760 non-null   float64
 6   Wind Speed          8760 non-null   float64
 7   Wind Direction      8760 non-null   float64
 8   Pressure            8760 non-null   float64
 9   Solar Zenith Angle  8760 non-null   float64
 10  DNI                 8760 non-null   float64
 11  GHI                 8760 non-null   float64
 12  DHI                 8760 non-null   float64
 13  Relative Humidity   8760 non-null   float64
 14  Dew Point           8760 non-null   float64
 15  Hour_sin            8760 non-null   float64
 16  Hour_cos            8760 non-null   float64
 17  DayOfYear           8760 non-null   float64
 18  Target_GHI          8760 non-null   float64
 19  POA_Irradiance      8760 non-null   float64
 20  PV_Output_kW        8760 non-null   float64
 21  PV_target           8759 non-null   float64
dtypes: float64(22)
memory usage: 1.5 MB

In [ ]:
df.head(10)

,Year,Month,Day,Hour,Minute,Temperature,Wind Speed,Wind Direction,Pressure,Solar Zenith Angle,...,DHI,Relative Humidity,Dew Point,Hour_sin,Hour_cos,DayOfYear,Target_GHI,POA_Irradiance,PV_Output_kW,PV_target
datetime,,,,,,,,,,,,,,,,,,,,,
2018-01-01 00:00:00,2018.0,1.0,1.0,0.0,22.5,10.600,1.675,328.75,1018.00,163.2675,...,0.00,81.2675,7.525,0.000000,1.000000e+00,1.0,0.00,0.000000,0.000000,0.000000
2018-01-01 01:00:00,2018.0,1.0,1.0,1.0,22.5,10.000,1.725,334.00,1018.00,149.4975,...,0.00,82.5175,7.200,0.258819,9.659258e-01,1.0,0.00,0.000000,0.000000,0.000000
2018-01-01 02:00:00,2018.0,1.0,1.0,2.0,22.5,9.475,1.800,340.25,1018.00,135.8175,...,0.00,83.2425,6.800,0.500000,8.660254e-01,1.0,62.25,0.000000,0.000000,0.000000
2018-01-01 03:00:00,2018.0,1.0,1.0,3.0,22.5,8.975,1.900,346.25,1018.00,122.2775,...,0.00,83.7800,6.400,0.707107,7.071068e-01,1.0,249.00,0.000000,0.000000,0.000000
2018-01-01 04:00:00,2018.0,1.0,1.0,4.0,22.5,8.600,1.900,350.00,1018.00,108.9450,...,0.00,84.2300,6.100,0.866025,5.000000e-01,1.0,431.25,0.000000,0.000000,0.000000
2018-01-01 05:00:00,2018.0,1.0,1.0,5.0,22.5,12.075,1.675,341.75,1012.75,95.9600,...,0.00,95.1325,11.325,0.965926,2.588190e-01,1.0,573.25,0.000000,0.000000,10.183464
2018-01-01 06:00:00,2018.0,1.0,1.0,6.0,22.5,13.700,2.300,344.00,1013.50,83.2825,...,41.50,87.0550,11.575,1.000000,6.123234e-17,1.0,558.75,127.293303,10.183464,35.107473
2018-01-01 07:00:00,2018.0,1.0,1.0,7.0,22.5,15.750,2.300,345.50,1014.00,71.6350,...,110.50,79.1700,12.175,0.965926,-2.588190e-01,1.0,405.00,438.843407,35.107473,51.937981
2018-01-01 08:00:00,2018.0,1.0,1.0,8.0,22.5,18.725,1.675,351.50,1014.00,61.1225,...,150.50,71.8250,13.550,0.866025,-5.000000e-01,1.0,383.50,649.224766,51.937981,62.303144
2018-01-01 09:00:00,2018.0,1.0,1.0,9.0,22.5,21.725,1.275,354.25,1013.75,52.5650,...,174.25,62.4950,14.250,0.707107,-7.071068e-01,1.0,218.75,778.789303,62.303144,52.500041

In [ ]:
df.columns

Index(['Year', 'Month', 'Day', 'Hour', 'Minute', 'Temperature', 'Wind Speed',
       'Wind Direction', 'Pressure', 'Solar Zenith Angle', 'DNI', 'GHI', 'DHI',
       'Relative Humidity', 'Dew Point', 'Hour_sin', 'Hour_cos', 'DayOfYear',
       'Target_GHI', 'POA_Irradiance', 'PV_Output_kW', 'PV_target'],
      dtype='object')

In [ ]:
# Download the df DataFrame to a CSV file
df.to_csv('df_with_pv_data.csv', index=True)
print("DataFrame 'df' saved to 'df_with_pv_data.csv'. You can download it from the files section.")

DataFrame 'df' saved to 'df_with_pv_data.csv'. You can download it from the files section.